---
global:
  imageRegistry:
  labels:
inventree:
  admin:
    username: "admin"
    email: "admin@localhost"
    # You can set the admin password either way below.  
    # Regardless of the method, it is suggested you rotate the password once 
    # the app is started as this value will be accesisble via an environment variable.

    # clear text initial password for admin user - ignored if `passwordFromSecret` is set
    password: "admin"
    # optionally, you can choose to set the password from a Kubernetes secret
    passwordFromSecret:
      sercretName:
      namespace:

server:
  image:
    repository: "inventree/inventree"
    tag: "0.7.4"
    pullPolicy:
worker:
  image:
    repository: "inventree/inventree"
    tag: "0.7.4"
    pullPolicy:
redis:
  labels:
  image:
    repository: "redis"
    tag: "7.0"
    pullPolicy:

postgres:
  image:
    repository: "postgres"
    tag: "13"
    pullPolicy:

proxy:
  image:
    repository: "nginx"
    tag: "stable"
    pullPolicy:

ingress:
  enabled: false
  labels:
  annotations:
  host: ""
  path: "/"


#traefik ingressRoute - only use if you have a traefik ingress
ingressRoute:
  enabled: false
  labels:
  tls:
    enabled: true
    config:
      certResolver: acme
  entryPoint: "web"
  tlsEntryPoint: "web-secured"
  host: ""
  annotations:
  httpMiddlewares:
    # - name: httpsredirect
    #   namespace: default




nameOverride: ""
fullnameOverride: ""

