---
global:
  imageRegistry:
  labels:
server:
  image:
    repository: "inventree/inventree"
    tag: "0.7.4"
    pullPolicy:
worker:
  image:
    repository: "inventree/inventree"
    tag: "0.7.4"
    pullPolicy:
redis:
  labels:
  image:
    repository: "redis"
    tag: "7.0"
    pullPolicy:

postgres:
  image:
    repository: "postgres"
    tag: "13"
    pullPolicy:

proxy:
  image:
    repository: "nginx"
    tag: "stable"
    pullPolicy:

ingress:
  enabled: false
  labels:
  annotations:
  host: ""
  path: "/"


#traefik ingressRoute - only use if you have a traefik ingress
ingressRoute:
  enabled: false
  labels:
  tls: []
  hosts: ""
  annotations:



nameOverride: ""
fullnameOverride: ""

