apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    io.kompose.service: {{ include "inventree.name" . }}-db
  name: {{ include "inventree.name" . }}-db
spec:
  ports:
  - name: "postgres"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: {{ include "inventree.name" . }}-db

