apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    io.kompose.service: {{ include "inventree.name" . }}-db
  name: {{ include "inventree.fullname" . }}-db
spec:
  podManagementPolicy: OrderedReady
  serviceName: {{ include "inventree.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ include "inventree.name" . }}-db
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: {{ include "inventree.name" . }}-db
    spec:
      containers:
      - image: postgres:13
        imagePullPolicy: ""
        name: {{ include "inventree.fullname" . }}-db
        ports:
          - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: {{ include "inventree.fullname" . }}-db
        envFrom:
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-postgres-config
        - secretRef:
            name: {{ include "inventree.fullname" . }}-postgres-secret
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: {{ include "inventree.fullname" . }}-db
        persistentVolumeClaim:
          claimName: {{ include "inventree.fullname" . }}-db
