apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: {{ include "inventree.fullname" . }}-db
  name: {{ include "inventree.fullname" . }}-db
spec:
  podManagementPolicy: OrderedReady
  serviceName: {{ include "inventree.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "inventree.fullname" . }}-db
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/component: {{ include "inventree.fullname" . }}-db
    spec:
      containers:
      - image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: "{{ .Values.postgres.image.pullPolicy }}"
        name: {{ include "inventree.fullname" . }}-db
        ports:
          - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: {{ include "inventree.fullname" . }}-db
        envFrom:
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-postgres-config
        - secretRef:
            name: {{ include "inventree.fullname" . }}-postgres-secret
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: {{ include "inventree.fullname" . }}-db
        persistentVolumeClaim:
          claimName: {{ include "inventree.fullname" . }}-db
