apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  annotations:
  labels:
  namespace: inventree
data:
  PGDATA: "/var/lib/postgresql/data/pgdb"
  POSTGRES_DB: "inventree"
  POSTGRES_USER: "pguser"
