apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventree.fullname" . }}-postgres-config
  annotations: {}
  labels:
data:
  PGDATA: "/var/lib/postgresql/data/pgdb"
  POSTGRES_DB: "inventree"
  POSTGRES_USER: "pguser"
