apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: {{ include "inventree.fullname" . }}-db
  name: {{ include "inventree.fullname" . }}-db
spec:
  ports:
  - name: "postgres"
    port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/component: {{ include "inventree.fullname" . }}-db

