apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ include "inventree.name" . }}-db
  name: {{ include "inventree.name" . }}-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

