apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: {{ include "inventree.fullname" . }}-proxy
  name: {{ include "inventree.fullname" . }}-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "inventree.fullname" . }}-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/component: {{ include "inventree.fullname" . }}-proxy
    spec:
      containers:
      - image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
        imagePullPolicy: "{{ .Values.proxy.image.pullPolicy }}"
        name: {{ include "inventree.fullname" . }}-proxy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: inventree-proxy-config
          readOnly: true
        - mountPath: /var/www
          name: inventree-data
          readOnly: true
        envFrom:
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-config
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-db-client-config
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: inventree-proxy-config
        configMap:
          name: {{ include "inventree.fullname" . }}-proxy-config
          defaultMode: 420
      - name: inventree-data
        persistentVolumeClaim:
          claimName: {{ include "inventree.fullname" . }}-data
