apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    io.kompose.service: {{ include "inventree.name" . }}-proxy
  name: {{ include "inventree.fullname" . }}-proxy
spec:
  ports:
  - name: "web"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: {{ include "inventree.name" . }}-proxy

