apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventree.fullname" . }}-db-client-config
  annotations: {}
  labels:
data:
  INVENTREE_DB_ENGINE: postgresql
  INVENTREE_DB_HOST: {{ include "inventree.fullname" . }}-db.{{- .Release.Namespace -}}.svc.cluster.local
  INVENTREE_DB_NAME: inventree
  INVENTREE_DB_PORT: "5432"
  INVENTREE_DB_USER: pguser
