apiVersion: v1
kind: ConfigMap
metadata:
  name: inventree-db-client-config
  annotations:
  labels:
  namespace: inventree
data:
  INVENTREE_DB_ENGINE: postgresql
  INVENTREE_DB_HOST: inventree-db.inventree.svc.cluster.local
  INVENTREE_DB_NAME: inventree
  INVENTREE_DB_PORT: "5432"
  INVENTREE_DB_USER: pguser
