apiVersion: v1
kind: ConfigMap
metadata:
  name: inventree-config
  annotations:
  labels:
  namespace: inventree
data:
  INVENTREE_CACHE_HOST: inventree-cache.inventree.svc.cluster.local
  INVENTREE_CACHE_PORT: "6379"
  INVENTREE_DEBUG: "False"
  INVENTREE_LOG_LEVEL: WARNING
  INVENTREE_PLUGINS_ENABLED: "False"