apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventree.fullname" . }}-config
  annotations: {}
  labels:
data:
  INVENTREE_CACHE_HOST: {{ include "inventree.fullname" . }}-cache.{{ .Release.Namespace }}.svc.cluster.local
  INVENTREE_CACHE_PORT: "6379"
  INVENTREE_DEBUG: "False"
  INVENTREE_LOG_LEVEL: WARNING
  INVENTREE_PLUGINS_ENABLED: "False"