apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventree.fullname" . }}-config
  annotations: {}
  labels:
data:
  INVENTREE_CACHE_HOST: {{ include "inventree.fullname" . }}-cache.{{ .Release.Namespace }}.svc.cluster.local
  INVENTREE_CACHE_PORT: "6379"
  INVENTREE_DEBUG: "False"
  INVENTREE_LOG_LEVEL: WARNING
  INVENTREE_PLUGINS_ENABLED: "False"
  INVENTREE_ADMIN_USER: {{ .Values.inventree.admin.username }}
  INVENTREE_ADMIN_EMAIL: {{ .Values.inventree.admin.email }}
# {{- if .Values.inventree.admin.passwordFromSecret.secretName -}}
# {{- else -}}
  INVENTREE_ADMIN_PASSWORD: {{ .Values.inventree.admin.password }}
# {{- end -}}