apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    io.kompose.service: {{ include "inventree.name" . }}-server
  name: {{ include "inventree.name" . }}-server
spec:
  podManagementPolicy: OrderedReady
  serviceName: {{ include "inventree.name" . }}-server
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ include "inventree.name" . }}-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f resolved.yaml -v -c -o result
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: {{ include "inventree.name" . }}-server
    spec:
      initContainers:
      - image: inventree/inventree:stable
        imagePullPolicy: ""
        name: {{ include "inventree.name" . }}-provison-db
        resources: {}
        volumeMounts:
          - mountPath: /home/inventree/data
            name: {{ include "inventree.name" . }}-data
        args:
          - invoke
          - update
        env:
        - name: INVENTREE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "inventree.name" . }}-postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: {{ include "inventree.name" . }}-config
        - configMapRef:
            name: {{ include "inventree.name" . }}-db-client-config
      containers:
      - image: inventree/inventree:stable
        imagePullPolicy: ""
        name: {{ include "inventree.name" . }}-server
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /home/inventree/data
          name: {{ include "inventree.name" . }}-data
        env:
        - name: INVENTREE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "inventree.name" . }}-postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: {{ include "inventree.name" . }}-config
        - configMapRef:
            name: {{ include "inventree.name" . }}-db-client-config
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: {{ include "inventree.name" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "inventree.name" . }}-data
