apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: {{ include "inventree.fullname" . }}-server
  name: {{ include "inventree.fullname" . }}-server
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/component: {{ include "inventree.fullname" . }}-server

