apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    io.kompose.service: {{ include "inventree.fullname" . }}-server
  name: {{ include "inventree.fullname" . }}-server
spec:
  podManagementPolicy: OrderedReady
  serviceName: {{ include "inventree.fullname" . }}-server
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "inventree.fullname" . }}-server
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/component: {{ include "inventree.fullname" . }}-server
    spec:
      initContainers:
      - image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
        name: {{ include "inventree.fullname" . }}-provison-db
        resources: {}
        volumeMounts:
          - mountPath: /home/inventree/data
            name: {{ include "inventree.fullname" . }}-data
        args:
          - invoke
          - update
        env:
        - name: INVENTREE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "inventree.fullname" . }}-postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-config
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-db-client-config
      containers:
      - image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
        name: {{ include "inventree.fullname" . }}-server
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /home/inventree/data
          name: {{ include "inventree.fullname" . }}-data
        env:
        - name: INVENTREE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "inventree.fullname" . }}-postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-config
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-db-client-config
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: {{ include "inventree.fullname" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "inventree.fullname" . }}-data
