apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: inventree-worker
  name: inventree-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inventree-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f resolved.yaml -v -c -o result
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: inventree-worker
    spec:
      containers:
      - args:
        - invoke
        - worker
        env:
        - name: INVENTREE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "inventree.name" . }}-postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: {{ include "inventree.name" . }}-config
        - configMapRef:
            name: {{ include "inventree.name" . }}-db-client-config
        image: inventree/inventree:stable
        imagePullPolicy: ""
        name: inventree-worker
        resources: {}
        volumeMounts:
        - mountPath: /home/inventree/data
          name: inventree-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: inventree-data
        persistentVolumeClaim:
          claimName: inventree-data
