apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ include "inventree.fullname" . }}-worker
  name: {{ include "inventree.fullname" . }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ include "inventree.fullname" . }}-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: {{ include "inventree.fullname" . }}-worker
    spec:
      containers:
      - args:
        - invoke
        - worker
        env:
        - name: INVENTREE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "inventree.fullname" . }}-postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-config
        - configMapRef:
            name: {{ include "inventree.fullname" . }}-db-client-config
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: "{{ .Values.worker.image.pullPolicy }}"
        name: inventree-worker
        resources: {}
        volumeMounts:
        - mountPath: /home/inventree/data
          name: inventree-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: inventree-data
        persistentVolumeClaim:
          claimName: {{ include "inventree.fullname" . }}-data
